#!/usr/bin/env sh
echo "Starting default VM session at `date`..."
vmconsole -c start_session
echo "Waiting for ten minutes for the VMs to be ready..."
sleep 600
echo "Running ten random attack chains..."
generateattackchains -i 10 -s 12345 > sample_attack_chains
attackconsole -l sample_simulation.log < sample_attack_chains
echo "Attacks finished at `date`."
read -p "Press Enter to power off and restore all VMs:"
vmconsole -c close_session
