---
#
# Adds externalmailhandler systemd service and enables it to run on startup
# Additionally, creates a logrotate config file for logs
#

- name: Download binutils package
  get_url:
    url: "https://old.kali.org/kali/pool/main/b/binutils/binutils_2.43.1-5_amd64.deb"
    dest: "/tmp/binutils_2.43.1-5_amd64.deb"

- name: Install binutils package
  apt:
    deb: "/tmp/binutils_2.43.1-5_amd64.deb"

- name: Download python3-aiosmtpd package
  get_url:
    url: "https://old.kali.org/kali/pool/main/p/python-aiosmtpd/python3-aiosmtpd_1.4.6-1_all.deb"
    dest: "/tmp/python3-aiosmtpd_1.4.6-3_all.deb"

- name: Install python3-aiosmtpd package
  apt:
    deb: "/tmp/python3-aiosmtpd_1.4.6-3_all.deb"

- name: "Create script directory {{ script_dir }}"
  file:
    path: "{{ script_dir }}"
    state: directory

- name: "Copy the script to fixed destination"
  copy:
    src: "../files/{{ script }}"
    dest: "{{ script_path }}"

- name: "Create log directory {{ log_dir }}"
  file:
    path: "{{ log_dir }}"
    state: directory

- name: "Create logrotate config"
  blockinfile:
    path: "{{ logrotate_config_path }}"
    create: yes
    block: |
      /var/log/breach/external_mail_handler.log {
        daily
        rotate 365
        create
        missingok
        notifempty
      }

- name: "Install script as a systemd service file"
  template:
    src: "../templates/{{ service_name }}.service.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: '0664'

- name: "Force systemd to reread configs and enable the script to run at startup"
  systemd:
    name: "{{ service_name }}"
    daemon_reload: yes
    enabled: yes
    state: started
