---
#
# Adds externalmailhandler systemd service and enables it to run on startup
# Additionally, creates a logrotate config file for logs
#

- name: Add specific Kali Linux repository
  apt_repository:
    repo: "deb http://old.kali.org/kali 2024.4 main contrib non-free"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Ensure compatible version of binutils
  apt:
    name: binutils=2.43.1-5
    state: present
    
- name: Install aiosmtpd (requirement) globally
  apt:
    name: python3-aiosmtpd=1.4.6-3
    state: present

- name: "Create script directory {{ script_dir }}"
  file:
    path: "{{ script_dir }}"
    state: directory

- name: "Copy the script to fixed destination"
  copy:
    src: "../files/{{ script }}"
    dest: "{{ script_path }}"

- name: "Create log directory {{ log_dir }}"
  file:
    path: "{{ log_dir }}"
    state: directory

- name: "Create logrotate config"
  blockinfile:
    path: "{{ logrotate_config_path }}"
    create: yes
    block: |
      /var/log/breach/external_mail_handler.log {
        daily
        rotate 365
        create
        missingok
        notifempty
      }

- name: "Install script as a systemd service file"
  template:
    src: "../templates/{{ service_name }}.service.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: '0664'

- name: "Force systemd to reread configs and enable the script to run at startup"
  systemd:
    name: "{{ service_name }}"
    daemon_reload: yes
    enabled: yes
    state: started
