---

- name: Install NTP
  apt:
    name: ntp=1:4.2.8p18+dfsg-2~1.2.3+dfsg1-3
    allow_downgrade: yes

- name: Disable default NTP servers
  replace:
    path: /etc/ntp.conf
    regexp: '^(server|pool)(.*)$'
    replace: '#\1\2'

- name: "Add authoritative NTP server {{ authoritative_ntp_server }}"
  lineinfile:
    path: /etc/ntp.conf
    line: "server {{ authoritative_ntp_server }} iburst"
    state: present

- name: Enable ntpstats
  replace:
    path: /etc/ntp.conf
    regexp: '#statsdir /var/log/ntpstats/'
    replace: 'statsdir /var/log/ntpstats/'

- name: Restart ntp service
  service:
    name: ntp
    daemon_reload: yes
    enabled: yes
    state: restarted
