#!/usr/bin/env bash
samba-tool user add client1 breach
samba-tool user setexpiry client1 --noexpiry
samba-tool group addmembers "Domain Admins" client1
samba-tool user add client2 breach
samba-tool user setexpiry client2 --noexpiry
samba-tool user add client3 breach
samba-tool user setexpiry client3 --noexpiry
samba-tool user add client4 breach
samba-tool user setexpiry client4 --noexpiry
samba-tool user add client5 breach
samba-tool user setexpiry client5 --noexpiry
samba-tool user add client6 breach
samba-tool user setexpiry client6 --noexpiry
samba-tool user add client7 breach
samba-tool user setexpiry client7 --noexpiry
samba-tool user add client8 breach
samba-tool user setexpiry client8 --noexpiry
samba-tool user add client9 breach
samba-tool user setexpiry client9 --noexpiry
samba-tool user add client10 breach
samba-tool user setexpiry client10 --noexpiry
samba-tool user add client11 breach
samba-tool user setexpiry client11 --noexpiry
samba-tool user add client12 breach
samba-tool user setexpiry client12 --noexpiry
samba-tool user add client13 breach
samba-tool user setexpiry client13 --noexpiry
samba-tool user add client14 breach
samba-tool user setexpiry client14 --noexpiry
samba-tool user add client15 breach
samba-tool user setexpiry client15 --noexpiry
samba-tool user add client16 breach
samba-tool user setexpiry client16 --noexpiry
samba-tool user add client17 breach
samba-tool user setexpiry client17 --noexpiry
samba-tool user add client18 breach
samba-tool user setexpiry client18 --noexpiry
samba-tool user add client19 breach
samba-tool user setexpiry client19 --noexpiry
samba-tool user add client20 breach
samba-tool user setexpiry client20 --noexpiry
samba-tool user add client21 breach
samba-tool user setexpiry client21 --noexpiry
samba-tool user add client22 breach
samba-tool user setexpiry client22 --noexpiry
samba-tool user add client23 breach
samba-tool user setexpiry client23 --noexpiry
samba-tool user add client24 breach
samba-tool user setexpiry client24 --noexpiry
samba-tool user add client25 breach
samba-tool user setexpiry client25 --noexpiry
samba-tool user add client26 breach
samba-tool user setexpiry client26 --noexpiry
samba-tool user add client27 breach
samba-tool user setexpiry client27 --noexpiry
samba-tool user add client28 breach
samba-tool user setexpiry client28 --noexpiry
samba-tool user add client29 breach
samba-tool user setexpiry client29 --noexpiry
samba-tool user add client30 breach
samba-tool user setexpiry client30 --noexpiry
samba-tool user add client31 breach
samba-tool user setexpiry client31 --noexpiry
samba-tool user add client32 breach
samba-tool user setexpiry client32 --noexpiry
samba-tool user add client33 breach
samba-tool user setexpiry client33 --noexpiry
samba-tool user add client34 breach
samba-tool user setexpiry client34 --noexpiry
samba-tool user add client35 breach
samba-tool user setexpiry client35 --noexpiry
samba-tool user add client36 breach
samba-tool user setexpiry client36 --noexpiry
samba-tool user add client37 breach
samba-tool user setexpiry client37 --noexpiry
samba-tool user add client38 breach
samba-tool user setexpiry client38 --noexpiry
samba-tool user add client39 breach
samba-tool user setexpiry client39 --noexpiry
samba-tool user add client40 breach
samba-tool user setexpiry client40 --noexpiry
samba-tool user add client41 breach
samba-tool user setexpiry client41 --noexpiry
samba-tool user add client42 breach
samba-tool user setexpiry client42 --noexpiry
samba-tool user add client43 breach
samba-tool user setexpiry client43 --noexpiry
samba-tool user add client44 breach
samba-tool user setexpiry client44 --noexpiry
samba-tool user add client45 breach
samba-tool user setexpiry client45 --noexpiry
samba-tool user add client46 breach
samba-tool user setexpiry client46 --noexpiry
samba-tool user add client47 breach
samba-tool user setexpiry client47 --noexpiry
samba-tool user add client48 breach
samba-tool user setexpiry client48 --noexpiry
samba-tool user add client49 breach
samba-tool user setexpiry client49 --noexpiry
samba-tool user add client50 breach
samba-tool user setexpiry client50 --noexpiry
samba-tool user add client51 breach
samba-tool user setexpiry client51 --noexpiry
samba-tool user add client52 breach
samba-tool user setexpiry client52 --noexpiry
samba-tool user add client53 breach
samba-tool user setexpiry client53 --noexpiry
samba-tool user add client54 breach
samba-tool user setexpiry client54 --noexpiry
samba-tool user add client55 breach
samba-tool user setexpiry client55 --noexpiry
samba-tool user add client56 breach
samba-tool user setexpiry client56 --noexpiry
samba-tool user add client57 breach
samba-tool user setexpiry client57 --noexpiry
samba-tool user add client58 breach
samba-tool user setexpiry client58 --noexpiry
samba-tool user add client59 breach
samba-tool user setexpiry client59 --noexpiry
samba-tool user add client60 breach
samba-tool user setexpiry client60 --noexpiry
samba-tool user add client61 breach
samba-tool user setexpiry client61 --noexpiry
samba-tool user add client62 breach
samba-tool user setexpiry client62 --noexpiry
samba-tool user add client63 breach
samba-tool user setexpiry client63 --noexpiry
samba-tool user add client64 breach
samba-tool user setexpiry client64 --noexpiry
samba-tool user add client65 breach
samba-tool user setexpiry client65 --noexpiry
samba-tool user add client66 breach
samba-tool user setexpiry client66 --noexpiry
samba-tool user add client67 breach
samba-tool user setexpiry client67 --noexpiry
samba-tool user add client68 breach
samba-tool user setexpiry client68 --noexpiry
samba-tool user add client69 breach
samba-tool user setexpiry client69 --noexpiry
samba-tool user add client70 breach
samba-tool user setexpiry client70 --noexpiry
samba-tool user add client71 breach
samba-tool user setexpiry client71 --noexpiry
samba-tool user add client72 breach
samba-tool user setexpiry client72 --noexpiry
samba-tool user add client73 breach
samba-tool user setexpiry client73 --noexpiry
samba-tool user add client74 breach
samba-tool user setexpiry client74 --noexpiry
samba-tool user add client75 breach
samba-tool user setexpiry client75 --noexpiry
samba-tool user add client76 breach
samba-tool user setexpiry client76 --noexpiry
samba-tool user add client77 breach
samba-tool user setexpiry client77 --noexpiry
samba-tool user add client78 breach
samba-tool user setexpiry client78 --noexpiry
samba-tool user add client79 breach
samba-tool user setexpiry client79 --noexpiry
samba-tool user add client80 breach
samba-tool user setexpiry client80 --noexpiry
samba-tool user add client81 breach
samba-tool user setexpiry client81 --noexpiry
samba-tool user add client82 breach
samba-tool user setexpiry client82 --noexpiry
samba-tool user add client83 breach
samba-tool user setexpiry client83 --noexpiry
samba-tool user add client84 breach
samba-tool user setexpiry client84 --noexpiry
samba-tool user add client85 breach
samba-tool user setexpiry client85 --noexpiry
samba-tool user add client86 breach
samba-tool user setexpiry client86 --noexpiry
samba-tool user add client87 breach
samba-tool user setexpiry client87 --noexpiry
samba-tool user add client88 breach
samba-tool user setexpiry client88 --noexpiry
samba-tool user add client89 breach
samba-tool user setexpiry client89 --noexpiry
samba-tool user add client90 breach
samba-tool user setexpiry client90 --noexpiry
samba-tool user add client91 breach
samba-tool user setexpiry client91 --noexpiry
samba-tool user add client92 breach
samba-tool user setexpiry client92 --noexpiry
samba-tool user add client93 breach
samba-tool user setexpiry client93 --noexpiry
samba-tool user add client94 breach
samba-tool user setexpiry client94 --noexpiry
samba-tool user add client95 breach
samba-tool user setexpiry client95 --noexpiry
samba-tool user add client96 breach
samba-tool user setexpiry client96 --noexpiry
samba-tool user add client97 breach
samba-tool user setexpiry client97 --noexpiry
samba-tool user add client98 breach
samba-tool user setexpiry client98 --noexpiry
samba-tool user add client99 breach
samba-tool user setexpiry client99 --noexpiry
samba-tool user add client100 breach
samba-tool user setexpiry client100 --noexpiry
