#!/usr/bin/env bash

printf "Starting build. Please allow up to 120 minutes.\n"
./tools/cleanup_failed_session  > /dev/null 2>&1

printf "Building userbehavior.pex file.\n"
cd ./src/userbehavior
../../../bin/pex . -c userbehavior -o ../../provisioning/ansible/roles/configure_win10_client/files/win10_assets/userbehavior.pex --disable-cache
cd ../../

vboxmanage startvm "Internet Router" --type headless
vboxmanage startvm "Company Router" --type headless
vboxmanage startvm "Log Server" --type headless
export ANSIBLE_HOST_KEY_CHECKING=False
cd ./provisioning/packer/

if [ -n "$1" ] && [ $1 == "runner" ]; then
export PACKER_CACHE_DIR=/usr/share/runner-dependencies/packer_cache
packer build -force -var 'vm_output=/usr/share/runner-dependencies/virtual_machines/client' client.json
else
packer build -force client.json
fi

if [ $? != 0 ]; then
	printf "Packer exited with non-zero return code.\nResetting all previously built machines to their old snapshots...\n"
	../../tools/cleanup_failed_session  > /dev/null 2>&1
	exit 1
fi

vboxmanage controlvm "Log Server" acpipowerbutton
echo "Waiting until Log Server shuts down completely before taking snapshot..."

for i in {1..300}; do
  sleep 1
  if ! vboxmanage list runningvms | grep -q "Log Server"; then
    break
  fi
done
sleep 5

vboxmanage snapshot "Log Server" edit "fresh" --name "pre_client_build"
vboxmanage snapshot "Log Server" take "fresh"

cd ../..
./tools/cleanup_failed_session  > /dev/null 2>&1
printf "Task finished.\n\n"
